version: '3'

services: 
    mysql:
        container_name: mysql
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        hostname: mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        # mysqlの設定
        env_file: ./docker/mysql/.env
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
        volumes:
            - db-data:/var/lib/mysql
            # 初期設定を読み込む
            - ./docker/mysql/mysql.conf:/etc/mysql/mysql.conf
            # MySQL起動時にDBを作成する
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - ./log/mysql:/var/log/mysql
    app:
        # mysqlのコンテナとリンク付けする
        links:
            - mysql
        build: 
            context: .
            dockerfile: ./docker/golang/Dockerfile
        container_name: app
        ports: 
            - "8080:8080"
        volumes: 
            - .:/go/src/github.com/nanimowakaran6/fugou_2020_01
        command: sh ./src/start_app.sh
volumes: 
    db-data:
        driver: local